### ISSUE TITLE
ImportError: cannot import name 'Chain' from 'chainconsumer'

### ISSUE THREAD

**Issue by am610** [Samreay/ChainConsumer#102]
When I try 

`from chainconsumer import ChainConsumer, Chain`

I get import error for `Chain`

`ImportError: cannot import name 'Chain' from 'chainconsumer' (/Users/user/opt/anaconda3/lib/python3.9/site-packages/chainconsumer/__init__.py)`

I tried this in two different systems, got the same error.

Installation done as : `pip install chainconsumer`

**Comment by renecotyfanboy** [comment]
Hi there! @Samreay is currently doing a gigantic refactoring for a transition to 1.0. The doc on https://samreay.github.io/ChainConsumer/ is now related to the version which is currently being developed, you might try to install it directly from GitHub using `pip install git+https://github.com/Samreay/ChainConsumer` until the next iteration of CC is deployed on pip. It might be unstable tho, but you are welcome to report any issues you're experiencing, so we can fix it until 1.0 is out!

**Comment by Samreay** [comment]
Apologies for the confusion, @am610. as @renecotyfanboy said, I'm doing a big python refactor because the original version was written to be py2.7 compatible, and a lot has changed since then. You can still pip install either via github, or via

```bash
pip install ---pre chainconsumer
```

I should hopefully have the proper v1.0.0 out soon, I'm mostly just gathering feedback for the new pydantic-heavy structure of the repo, so if you have thoughts when using as to things which could be done differently, please let me know. In the meantime, I'll close this comment out, and feel free to provide any thoughts about 1.0.0-rc1 [over here](https://github.com/Samreay/ChainConsumer/discussions/100)
