### ISSUE TITLE
diagnostic_gelman_rubin compted incorrectly

### ISSUE THREAD

**Issue by wmorning** [Samreay/ChainConsumer#21]
I've been playing around with ChainConsumer to examine mcmc data.  Its a great utility for visualizing, and processing chains, but I have noticed two issues in the Gelman Rubin diagnostic function.

The first is that when calculating the within sequence variance (W) you should take `np.std()**2` to get the variance rather than the standard deviation.  The variance is what Gelman & Rubin (1992:  https://projecteuclid.org/euclid.ss/1177011136), use to calculate W.  This distinction is important because unless your variance is very close to 1, you will either overestimate or underestimate W, which will cause you to either oversample or undersample your PDF (because the ratio B/W that is most important in determining convergence will be systematically overestimated or underestimated).  This gets really bad for chains which have a small sample variance (of order 0.001); such chains can appear to converge in as few as 110 MCMC steps, when they actually need ~10000.

The Second is that when calculating R, you should not be taking the square root of Var/W.  The Gelman & Rubin (1992) paper actually defines `sqrt(R) = sqrt(V/W df/(df-2))`, where df is some measure of the degrees of freedom (the way it is calculated is in their paper).  There are two implications of this:  1)  ChainConsumer is actually calculating `sqrt(R)`, which is always less than R, so it will always make chains appear more converged than they actually are.  2)  The value of R can decrease below 1 as long as `V/W` is sufficiently small (because it actually approaches `df-2/df`).  This is bad, because by definition, R cannot be less than 1, although the effect on determining convergence is negligible.

The fix should be pretty easy.  Just change line 1322 to be:
chain_std = `np.array([np.std(c,  axis=0)**2 for c in chains])`

and get the formula for df from the Gelman & Rubin paper, and adjust line 1326 to be 
R = `var / w * df / (df-2.)`

**Comment by Samreay** [comment]
Hi Warren, thanks for digging through the code. I based the algorithm off the 1998 Brooks & Gelman update instead of the 1992 Gelman & Rubin original paper, but you were right in that I made I mistake or two translating it into code.

You can see the changes in the commit referenced above, let me know if they look good. Have also compared the code implementations from my function and the PyMC and it seems they now do the same thing too.

If you're satisfied that it now looks correct, I'll release a new version of ChainConsumer with the update. Cheers!

**Comment by wmorning** [comment]
Looks good!  Go for it!

**Comment by Samreay** [comment]
v0.16.5 released. Thanks Warren.
