### ISSUE TITLE
x-axis limits

### ISSUE THREAD

**Issue by vvinuv** [Samreay/ChainConsumer#35]
Hi Admin

Can I limit x-axis values of the triangle subplots for different parameters? E.g. I have a truth value which is not appearing in the subplot and if I can limit the x-axis of the subplot for that particular parameter it will be helpful. I haven't found such a variable in the document and if I missed it could you please point that to me?

Thanks
vinu

**Comment by Samreay** [comment]
Hi Vinu,

If I've understood your issue, hopefully the `extents` kwarg can solve it. You can specify the plot limits using either a list of 2tuples, or you can specify them via a dictionary. ie if you have three parameters, (x,y,z) and want to configure the limits on the y parameter subplot, you would go

`c.plotter.plot(extents={"y": (-5,5)})`

Might have missed it because its a plotting config option, not a global chainconsumer config option (so not set in `configure`): https://samreay.github.io/ChainConsumer/chain_api.html#chainconsumer.plotter.Plotter.plot

**Comment by vvinuv** [comment]
Thanks Samreay! This is what I needed. Sorry for not carefully reading the document.

**Comment by Samreay** [comment]
No worries mate. Have a good one.

**Comment by cambash** [comment]
Hi admin,

This didn't work for me. Got the following error.

TypeError: plot() got an unexpected keyword argument 'extends'

Thanks
ash

**Comment by Samreay** [comment]
It should be `extents`, not `extends`

**Comment by cambash** [comment]
Yeah... Noticed it later. Sorry for disturbing you. Thanks a lot for the reply.

**Comment by Samreay** [comment]
No worries mate!

**Comment by sohinixcvii** [comment]
Hi admin! I am trying to use extents as well and it doesn't seem to be doing anything for my plot. Any ideas? (as in I get the same plot before and after adding extents to plot())

**Comment by Samreay** [comment]
Hi @sohinixcvii, could I get you to open this as a new [Github Discussion](https://github.com/Samreay/ChainConsumer/discussions) and throw perhaps just a hint of your code (and or data) in so I can have a gander?

**Comment by sohinixcvii** [comment]
> Hi @sohinixcvii, could I get you to open this as a new [Github Discussion](https://github.com/Samreay/ChainConsumer/discussions) and throw perhaps just a hint of your code (and or data) in so I can have a gander?

Hi! Thanks for the response, I have started a discussion and have attached some files to help you figure things out. Thank you so much! :)
