### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by steven-murray** [Samreay/ChainConsumer#39]
Hi Sam,

It would be nice if there was an option to scale up the fontsize when the figsize is scaled. For papers, it's nice to have the same fontsize regardless of the plot size, but for Jupyter notebooks etc, its nice to scale the font with the figure.

**Comment by Samreay** [comment]
I'm hesitant to add this one, because then there would be multiple ways of specifying the same thing, and I can definitely see it confusing some people that unwittingly set both or misunderstand how they work. The solution I used to keep fontsize legible in my iPython setups was to ensure the backend DPI was set to such a value that figures displayed easily readable without having to try and scale them up.

**Comment by steven-murray** [comment]
Yup OK I can roll with that.
