### ISSUE TITLE
Adding chain not in numpy array causes crash

### ISSUE THREAD

**Issue by matthewkirby** [Samreay/ChainConsumer#53]
When trying to make a corner plot from a chain that is not saved in a numpy array, it crashes.

```
trans_chain = [list(transform_chain(link)) for link in chain[:100]]
c = ChainConsumer()
c.add_chain(trans_chain, parameters=['p1', 'p2'])
fig = c.plotter.plot(figsize="column")
```

The error message I get is:

> File "/pythonpath/lib/python2.7/site-packages/chainconsumer/chain.py", line 51, in validate_chain
    (self.name, len(self.parameters), self.chain.shape[1])
AssertionError: Chain Chain 0 has 2 parameters but data has 100 columns

To fix it, I simply recast trans_chain as a numpy array. Opening issue because I felt that this would be easy to check for and then correct for when adding a chain.

**Comment by Samreay** [comment]
Hi Matthew, 

ChainConsumer should be fine with a python list in addition to a numpy array, and it will autoconvert a list into a numpy array. It looks like the main issue from your error log is that the list you are passing in has a shape of (dimensions, steps) rather than the required (steps, dimensions).

Essentially, if you pass in via a list, ChainConsumer expects a list of `len(dimensions)`, with each element of the top list being a list of values for that parameter per step, and this is because it allows people to each select columns out of a CSV file or unwrap a dictionary if they chose.
