### ISSUE TITLE
Aligning axis labels

### ISSUE THREAD

**Issue by vivekvenkris** [Samreay/ChainConsumer#62]
Hi @Samreay,
I have been using this package for a few weeks and it is excellent. 

I just had a small enhancement request:

As seen in the following image, if some of the distributions span negative and positive numbers while the others are always positive, the axis labels get offset in a weird way. Is there any way to make sure that the labels are aligned? 

I tried to `rcParams["axes.labelpad"] = <value>` but that pads everything the same way, so doesn't help.

Thanks,
Vivek 

![image](https://user-images.githubusercontent.com/8031603/42724696-5e22aeea-87ba-11e8-8c11-d9bbc1d359ea.png)

**Comment by vivekvenkris** [comment]
Maybe we could add a config option to ignore `tight_layout`? Will that work then?
I am not very experienced with Python but I thought it should be possible to get the range of values for each dimension, and if a few spans negative numbers then do a `plt.xlabel("...", labelpad=20)` or something for the rest of dimensions?

**Comment by Samreay** [comment]
Without `tight_layout`, many other aspects of the plotting break, so we cannot get rid of it. Similarly, the issue is more than just negative numbers, it would also happen if the scales of the numbers are different (-1 to 1 in one parameter, and -1000 to 1000 in another). Any fix would have to be generalised to cover all possible cases before it makes it in a release, which adds to the difficulty.

**Comment by vivekvenkris** [comment]
Ah right, yes. I understand. Anyway, please let me know if you find a way to do this for the general case. Until then I will try and hack my way to do it for just negative values. 

Thanks,
Vivek
