### ISSUE TITLE
Distinguishing groups of runs in plot_summary

### ISSUE THREAD

**Issue by caitlinadams** [Samreay/ChainConsumer#63]
Hey @Samreay,

I've been making use of the plot_summary feature to look at how marginalised constraints vary when I change different model parameters. I've been thinking about ways that this visualisation could be improved to more easily distinguish groups of runs that vary different parameters. I think this would be useful when testing multiple systematics, as you'd be able to see which systematic makes the most difference to the constraints since they'd all be plotted on the same axis.

For example, let's say I have some reference chain, and then I run two chains where I alter systematic 1 (Test A and B), and one chain where I alter systematic 2 (Test C). One way to distinguish between these would be to draw a horizontal line between the axes and add a label, such as in this mock-up I made quickly:
![sphx_glr_plot_summary_003](https://user-images.githubusercontent.com/25995927/44695291-d4281800-aab5-11e8-841f-5ee5c1d9529e.png)
Alternatively, you could use two colours -- one for the Sys 1 tests, and one for the Sys 2 tests.

It might be possible to implement the first suggestion through the existing code that sets up the frames in `plotter.py`:
```
# Set up the frames
if i > 0:
    ax.spines['top'].set_visible(False)
if i < (len(chains) - 1):
    ax.spines['bottom'].set_visible(False)
if i < (len(chains) - 1) or p in blind:
    ax.set_xticks([])
ax.set_yticks([])
ax.set_xlim(extents[p])
```
but there would need to be some indication from the chains about how the grouping works, such that you only use `set_visible(True)` at the boundry of the group. I suspect that this would also need to be the case if you wanted to apply the same colour to different groups of runs. 

I'm happy to investigate a solution to this, but was wondering if you had any thoughts about whether this was a useful thing to add. If yes, are there any particular thoughts you have about an appropriate visualisation and implementation?

Cheers,
Caitlin

**Comment by Samreay** [comment]
Hmmm yeah this shouldnt be a difficult feature code wise, just figuring out how it should all work. If its possible, avoiding adding extra data in the form of a designated group when adding the chain is ideal, because the method is already very bloated with kwargs which are mostly unused, and this would be another. Ill see if I can think of a way to do it without adding more bloat, but for now it does seem like the simplest way. Though it would require overriding manual sorting of the chains to ensure that groups are all done next to each other. 

At the moment, you can already specify the colour of the chains when adding them, so that might serve as an interim measure. 

I'll mull it over, for now the easiest thing would be to just grab the figure object from CC and add a line yourself. Or feel free to muck around with the internals, I just know I wont have time to get to it for a while, apologies :)

**Comment by caitlinadams** [comment]
I agree that it would be best to avoid bloating the method for adding chains. Like you say, it should be easy to specify the colours in advance. I hadn't thought about the fact that I could just add my own lines to the figure object -- I might try that out.

It might not be of enough use to have it internally coded as a feature, but I could write it up as an example for the docs if I can find a nice way to do it.

Thanks for your input!

**Comment by Samreay** [comment]
Imma see if I can squeeze this into the 1.0.0 release. Also, hi @caitlinadams, hope life outside academia treating you well!
