### ISSUE TITLE
Different marker styles in the same plot

### ISSUE THREAD

**Issue by tlittenberg** [Samreay/ChainConsumer#84]
I would like to be able to include several markers to the same figure while controlling the style for each individually.  I find when making repeated calls to add_marker, e.g.

c.add_marker(truth[0],...,marker_style='^') 
c.add_marker(truth[1],...,marker_style='+')

markers in the figure default to whichever was the first style specified.  Is there a work around?

**Comment by Samreay** [comment]
Hey Tyson,

I believe the same styles happen when you specify the same name for the markers. Essentially this happens because people have in the past wanted to load hundreds of chains in, but show the maximum point of each chain instead of the contour (useful for validating the statistical spread of simulations, etc).

If each marker has its own name, the styles should persist. The name being important is unintuitive though, so I'll see if I can implement some better behaviour. For an example that works for me giving different styles:

```
from chainconsumer import ChainConsumer
import matplotlib.pyplot as plt
import numpy as np
mean = np.array([1, 5])
cov = [[1, 1], [1, 3]]
parameters = ["a", "b"]

c = ChainConsumer()
c.add_covariance(mean, cov, parameters=parameters, name="Cov")
c.add_marker(mean, parameters=parameters, name="Marker1", marker_style="*", marker_size=100, color="r")
c.add_marker(mean+1, parameters=parameters, name="Marker2", marker_style="+", marker_size=100, color="k")
fig = c.plotter.plot()
plt.show()
```

**Comment by tlittenberg** [comment]
Ah ha!  Even better than what I was trying to do.  Thanks.

**Comment by Samreay** [comment]
Fantastic, glad it worked :)
